### ISSUE TITLE
3 unresolved externals?

### ISSUE THREAD

**Issue by Wearwolfy** [Jerem584/ARK-SDK#1]
I started with this as base hack with https://github.com/zH4x/SoT-DLL and now I am trying to implement this ark sdk.
And I am getting an error :(
![image](https://user-images.githubusercontent.com/21149078/84599390-fd27c180-ae71-11ea-81e5-80ca9fbdfb94.png)
Could you help me in any way?

**Comment by Jerem584** [comment]
#include "SDK/ARK_CoreUObject_functions.cpp"
#include "SDK/ARK_Engine_functions.cpp"
#include "SDK/ARK_ShooterGame_functions.cpp"
#include "SDK/ARK_Basic.cpp"

Include theses

**Comment by Wearwolfy** [comment]
Thanks for the help and fast response that managed to fix it and I was able to build it,
Now the dll is crashing upon loading it into the game I am guessing that I need to fix these but I am not sure?
![image](https://user-images.githubusercontent.com/21149078/84600644-33b60a00-ae7b-11ea-8136-db23ef389f3a.png)

**Comment by Jerem584** [comment]
> Thanks for the help and fast response that managed to fix it and I was able to build it,
> Now the dll is crashing upon loading it into the game I am guessing that I need to fix these but I am not sure?
> ![image](https://user-images.githubusercontent.com/21149078/84600644-33b60a00-ae7b-11ea-8136-db23ef389f3a.png)

Attach a debugger and see where it crash

**Comment by Wearwolfy** [comment]
Is this the crash log I am looking for?
![image](https://user-images.githubusercontent.com/21149078/84600888-dd49cb00-ae7c-11ea-823b-4dee7f3f6ea8.png)

**Comment by Jerem584** [comment]
Attach visual studio to shootergame and inject your dll using extreme injector loadlibrary

**Comment by Wearwolfy** [comment]
Thanks I am learning so fast all thanks to you <3, so after this error I am assuming that The offsets are wrong indeed
![image](https://user-images.githubusercontent.com/21149078/84601120-5bf33800-ae7e-11ea-81e8-c1e232576492.png)

**Comment by Wearwolfy** [comment]
Does the sdk have methods for getting Uworldoffset etc?
![image](https://user-images.githubusercontent.com/21149078/84601165-9f4da680-ae7e-11ea-96bf-021f2471fccf.png)

**Comment by Wearwolfy** [comment]
Cause I get this code but I don't know how u get the UworldOFF for example

**Comment by Wearwolfy** [comment]
Cause I get this code but I don't know how u get the UworldOFF for example or GNAMEOFF or GBOJECTSOFF
![image](https://user-images.githubusercontent.com/21149078/84601436-5bf43780-ae80-11ea-85a7-a812e4e8456d.png)

**Comment by Jerem584** [comment]
nah you need to get them sorry about that

**Comment by Wearwolfy** [comment]
Ok np do you have a good guide or a way to find them?

**Comment by Jerem584** [comment]
open ida go to names search for classes, (gworldproxy) boom you have addr

**Comment by Wearwolfy** [comment]
Yeah I found that on the forum, but don't you need all 3 for it to make a working hack?

**Comment by Jerem584** [comment]
only world to make a hack, names if you want to get any name (aka actor name) and gojbect is used to find classes and execute internal fnc

**Comment by Jerem584** [comment]
No wtf inject using extreme injevtor

**Comment by Wearwolfy** [comment]
I spent hours trying to find the Gobjects offset(cause i use internal hack), even tried with unRealfinderTool but was not able to find it? Could you give me a tip on how to find it?

**Comment by Jerem584** [comment]
> I spent hours trying to find the Gobjects offset(cause i use internal hack), even tried with unRealfinderTool but was not able to find it? Could you give me a tip on how to find it?

Open Ida and open names tab

**Comment by Wearwolfy** [comment]
And for what do I need to search in the names tab cause when I search GObject it returns multiple results while UWorldProxy returns a single result

**Comment by Wearwolfy** [comment]
Does the sdk still work since there is a new update?

**Comment by Jerem584** [comment]
updating it

**Comment by Wearwolfy** [comment]
Thanks alot :)

**Comment by Prxdd** [comment]
> Does the sdk still work since there is a new update?

Did you find the gobject

**Comment by Wearwolfy** [comment]
Yep just search for "GUObjectArray" in IDA PRO and u will get the offset( don't know how to get Gnames offset yet)
And what is causing this error?
![image](https://user-images.githubusercontent.com/21149078/84799469-98e53900-affc-11ea-8bf5-7832caf9eb7f.png)

**Comment by Prxdd** [comment]
> Yep just search for "GUObjectArray" in IDA PRO and u will get the offset( don't know how to get Gnames offset yet)
> And what is causing this error?
> ![image](https://user-images.githubusercontent.com/21149078/84799469-98e53900-affc-11ea-8bf5-7832caf9eb7f.png)

use x64dbg u can add me discord PrXd#1333

**Comment by Wearwolfy** [comment]
How to fix this? 
![image](https://user-images.githubusercontent.com/21149078/84814735-2e3ef800-b012-11ea-998e-01090358d80a.png)

**Comment by Jerem584** [comment]
> How to fix this?
> ![image](https://user-images.githubusercontent.com/21149078/84814735-2e3ef800-b012-11ea-998e-01090358d80a.png)

Copy old uobject class from old sdk and basic class too

**Comment by Wearwolfy** [comment]
So ARK_Basic.cpp and ARK_CoreUObject_functions.cpp or also the header files

**Comment by Jerem584** [comment]
> So ARK_Basic.cpp and ARK_CoreUObject_functions.cpp or also the header files

All the 6 files

**Comment by Jerem584** [comment]
Func struct param class + basic cpp + hpp

**Comment by Wearwolfy** [comment]
Copied these files from old sdk 
![image](https://user-images.githubusercontent.com/21149078/84820818-77934580-b01a-11ea-8389-0d31cf4335a8.png) and 
![image](https://user-images.githubusercontent.com/21149078/84820882-8ed23300-b01a-11ea-8361-56c0ef57c61d.png)
still getting this error 
![image](https://user-images.githubusercontent.com/21149078/84820898-9560aa80-b01a-11ea-9978-710dee91d53c.png)

**Comment by Wearwolfy** [comment]
I would very much appreciate your help I have gotten so far to getting my hack to work and tried everything you said :(

**Comment by Jerem584** [comment]
you can still use old sdk

**Comment by Bram-dc** [comment]
> Yep just search for "GUObjectArray" in IDA PRO and u will get the offset( don't know how to get Gnames offset yet)

You can find GNames by looking up the FName::GetNames in IDA

Gives you this:
![image](https://user-images.githubusercontent.com/13683918/87602304-0ae19880-c6f7-11ea-9d0f-8bcd8614802d.png)

which looks similar to this:

`TNameEntryArray& FName::GetNames()
{
	// NOTE: The reason we initialize to NULL here is due to an issue with static initialization of variables with
	// constructors/destructors across DLL boundaries, where a function called from a statically constructed object
	// calls a function in another module (such as this function) that creates a static variable.  A crash can occur
	// because the static initialization of this DLL has not yet happened, and the CRT's list of static destructors
	// cannot be written to because it has not yet been initialized fully.	(@todo UE4 DLL)
	static TNameEntryArray*	Names = NULL;
	if( Names == NULL )
	{
		check(IsInGameThread());
		Names = new TNameEntryArray();
	}
	return *Names;
}`

**Comment by Jerem584** [comment]
> > Yep just search for "GUObjectArray" in IDA PRO and u will get the offset( don't know how to get Gnames offset yet)
> 
> You can find GNames by looking up the FName::GetNames in IDA
> 
> Gives you this:
> ![image](https://user-images.githubusercontent.com/13683918/87602304-0ae19880-c6f7-11ea-9d0f-8bcd8614802d.png)
> 
> which looks similar to this:
> 
> TNameEntryArray& FName::GetNames()
> {
> static TNameEntryArray* Names = NULL;
> if( Names == NULL )
> {
> check(IsInGameThread());
> Names = new TNameEntryArray();
> }
> return *Names;
> }
Open Ida view →names and search for names
