### ISSUE TITLE
Progress

### ISSUE THREAD

**Issue by Bram-dc** [Jerem584/ARK-SDK#3]
Could you maybe update the sdk, or share your setup maybe privately?

**Comment by Bram-dc** [comment]
And could you maybe share me a general starting script, i have no clue how to start and get the offset to begin with. Im completely new to this subject. Maybe you have some links I could use to learn?

**Comment by Bram-dc** [comment]
![image](https://user-images.githubusercontent.com/13683918/87248973-ab685c00-c45c-11ea-8904-1588e3cebc5d.png)
 
Would you like to help me :)

**Comment by Bram-dc** [comment]
I know base and WorldOFF are variables i need to find, but do i need to find them manually using CheatEngine or other tools, or is there a better way to do it?

**Comment by Jerem584** [comment]
mhm if you pay i can explain you how to use sdk, and yeah will update once something is broken

**Comment by Bram-dc** [comment]
I will think about that, i will first experiment a bit

**Comment by Bram-dc** [comment]
> open ida go to names search for classes, (gworldproxy) boom you have addr

Did you mean UWorldProxy btw?
Since this is what i find in the source code: 
![image](https://user-images.githubusercontent.com/13683918/87304948-f6927580-c515-11ea-80d5-022cb664a8ff.png)

And still im not able to find it :(

**Comment by Jerem584** [comment]
You Need to search in ida

**Comment by Bram-dc** [comment]
![image](https://user-images.githubusercontent.com/13683918/87305949-956ba180-c517-11ea-9cb7-9d1fc5d63d31.png)

![Uploading image.png…]()



Do you get something else?

**Comment by Jerem584** [comment]
Uworld proxy also make sûre to load pdb

**Comment by Bram-dc** [comment]
Hm okay, maybe i forgot that, im reloading the files now

**Comment by Bram-dc** [comment]
![image](https://user-images.githubusercontent.com/13683918/87314187-2ac06300-c523-11ea-92de-f58a6a8e925e.png)
 Its not as easy as using this GWorld is it?

**Comment by Bram-dc** [comment]
![image](https://user-images.githubusercontent.com/13683918/87351293-84438480-c559-11ea-93c7-79403ec56b9b.png)

Would you mind helping me out once again solving this error? Im stuck on this for hours now.
