### ISSUE TITLE
Struct missing

### ISSUE THREAD

**Issue by Bram-dc** [Jerem584/ARK-SDK#4]
I created a new issue since this is not related to my other issues.

I think the struct 'UObject_FTransform', which if used in alot of functions. Should be 'FTransform' from ARK_CoreUObject_structs.hpp:255 instead.

Is this correct and should I just replace UObject_FTransform to FTransform?

**Comment by Jerem584** [comment]
Yes ????? Its just diff name

**Comment by Bram-dc** [comment]
I was getting errors that UObject_FTransform did not exists
